export const UPDATE_LAYOUT_SETTING = 'UPDATE_LAYOUT_SETTING';
export const UPDATE_SHORTCUT_LIST = 'UPDATE_SHORTCUT_LIST';
export const UPDATE_GLOBAL_SETTING = 'UPDATE_GLOBAL_SETTING';
export const UPDATE_BACKGROUND_IMAGE = 'UPDATE_BACKGROUND_IMAGE';
